### ISSUE TITLE
Web components in Firefox not working (window.customElements is undefined)

### ISSUE THREAD

**Issue by andrewhannum** [jsakas/Subtractor#36]
See here: https://stackoverflow.com/questions/40677265/how-to-get-custom-elements-working-in-firefox

**Comment by jsakas** [comment]
I am classifying this as an enhancement because we were aware that custom elements were not supported in FF when we decided to implement them. One of the project aspirations was to use no frameworks, but also to use some bleeding edge web technologies. 

It looks there is a polyfill available here: https://github.com/webcomponents/custom-elements

If it is a drop-in polyfill, meaning we don't have to change our code besides importing it into the global namespace, I think it satisfies our goal of truly having no frameworks used. Feel free to try it out and drop in a PR!

**Comment by andrewhannum** [comment]
Closing this issue. I didn't realize that it was an intentional decision to not support Firefox. Better to have a unified vision than me be the guy who's always trying to keep Firefox working.
